### ISSUE TITLE
Import data in chunks to limit memory usage

### ISSUE THREAD

**Issue by Vegter** [Amsterdam/GOB-Import#194]

**Comment by toolunious** [comment]
Proposed solution:


 1. Interface & implementation change: add a cursor context to `gobcore.database.reader.*` functions (either by adding a Strategy class per source type that holds this data or passing a context class) so we can seek & read (eg. SELECT FROM LIMIT 100,150 or  file.seek(100).read(50))
 2. Implementation change: have the reader class chunk the source data and yield from rows in each chunk.

I'd go for adding a new strategy abstract for interfacing with external datasources and have a factory method that would return a strategy by source type. `gobcore.reader` would be a repository handling the chunking/orchestration of reads & connects.

**Comment by Vegter** [comment]
Solved by import data in streams
